CREATE TABLE CarData (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vin VARCHAR(255),
  year INT,
  make VARCHAR(255),
  model VARCHAR(255),
  trim VARCHAR(255),
  dealer_name VARCHAR(255),
  dealer_street VARCHAR(255),
  dealer_city VARCHAR(255),
  dealer_state VARCHAR(255),
  dealer_zip  VARCHAR(255),
  listing_price DOUBLE,
  listing_mileage DOUBLE,
  used BOOLEAN,
  certified BOOLEAN,
  style VARCHAR(255),
  driven_wheels VARCHAR(255),
  engine VARCHAR(255),
  fuel_type  VARCHAR(255),
  exterior_color  VARCHAR(255),
  interior_color VARCHAR(255),
  seller_website VARCHAR(255),
  first_seen_date INT,
  last_seen_date INT,
  dealer_vdp_last_seen_date INT,
  listing_status VARCHAR(255)
);